// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"sync"

	"github.com/bborbe/github-release-watcher/pkg"
)

type Metrics struct {
	IncFilterSkippedStub        func(string)
	incFilterSkippedMutex       sync.RWMutex
	incFilterSkippedArgsForCall []struct {
		arg1 string
	}
	IncPollCycleStub        func(string)
	incPollCycleMutex       sync.RWMutex
	incPollCycleArgsForCall []struct {
		arg1 string
	}
	IncPublishedStub        func(string)
	incPublishedMutex       sync.RWMutex
	incPublishedArgsForCall []struct {
		arg1 string
	}
	IncReposScannedStub        func(int)
	incReposScannedMutex       sync.RWMutex
	incReposScannedArgsForCall []struct {
		arg1 int
	}
	IncWebhookDeliveryStub        func(string)
	incWebhookDeliveryMutex       sync.RWMutex
	incWebhookDeliveryArgsForCall []struct {
		arg1 string
	}
	IncWebhookSignatureRejectedStub        func()
	incWebhookSignatureRejectedMutex       sync.RWMutex
	incWebhookSignatureRejectedArgsForCall []struct {
	}
	IncWebhookSkippedStub        func(string)
	incWebhookSkippedMutex       sync.RWMutex
	incWebhookSkippedArgsForCall []struct {
		arg1 string
	}
	ObserveWebhookDispatchLatencyStub        func(float64)
	observeWebhookDispatchLatencyMutex       sync.RWMutex
	observeWebhookDispatchLatencyArgsForCall []struct {
		arg1 float64
	}
	SetRateLimitRemainingStub        func(int)
	setRateLimitRemainingMutex       sync.RWMutex
	setRateLimitRemainingArgsForCall []struct {
		arg1 int
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Metrics) IncFilterSkipped(arg1 string) {
	fake.incFilterSkippedMutex.Lock()
	fake.incFilterSkippedArgsForCall = append(fake.incFilterSkippedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncFilterSkippedStub
	fake.recordInvocation("IncFilterSkipped", []interface{}{arg1})
	fake.incFilterSkippedMutex.Unlock()
	if stub != nil {
		fake.IncFilterSkippedStub(arg1)
	}
}

func (fake *Metrics) IncFilterSkippedCallCount() int {
	fake.incFilterSkippedMutex.RLock()
	defer fake.incFilterSkippedMutex.RUnlock()
	return len(fake.incFilterSkippedArgsForCall)
}

func (fake *Metrics) IncFilterSkippedCalls(stub func(string)) {
	fake.incFilterSkippedMutex.Lock()
	defer fake.incFilterSkippedMutex.Unlock()
	fake.IncFilterSkippedStub = stub
}

func (fake *Metrics) IncFilterSkippedArgsForCall(i int) string {
	fake.incFilterSkippedMutex.RLock()
	defer fake.incFilterSkippedMutex.RUnlock()
	argsForCall := fake.incFilterSkippedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncPollCycle(arg1 string) {
	fake.incPollCycleMutex.Lock()
	fake.incPollCycleArgsForCall = append(fake.incPollCycleArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncPollCycleStub
	fake.recordInvocation("IncPollCycle", []interface{}{arg1})
	fake.incPollCycleMutex.Unlock()
	if stub != nil {
		fake.IncPollCycleStub(arg1)
	}
}

func (fake *Metrics) IncPollCycleCallCount() int {
	fake.incPollCycleMutex.RLock()
	defer fake.incPollCycleMutex.RUnlock()
	return len(fake.incPollCycleArgsForCall)
}

func (fake *Metrics) IncPollCycleCalls(stub func(string)) {
	fake.incPollCycleMutex.Lock()
	defer fake.incPollCycleMutex.Unlock()
	fake.IncPollCycleStub = stub
}

func (fake *Metrics) IncPollCycleArgsForCall(i int) string {
	fake.incPollCycleMutex.RLock()
	defer fake.incPollCycleMutex.RUnlock()
	argsForCall := fake.incPollCycleArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncPublished(arg1 string) {
	fake.incPublishedMutex.Lock()
	fake.incPublishedArgsForCall = append(fake.incPublishedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncPublishedStub
	fake.recordInvocation("IncPublished", []interface{}{arg1})
	fake.incPublishedMutex.Unlock()
	if stub != nil {
		fake.IncPublishedStub(arg1)
	}
}

func (fake *Metrics) IncPublishedCallCount() int {
	fake.incPublishedMutex.RLock()
	defer fake.incPublishedMutex.RUnlock()
	return len(fake.incPublishedArgsForCall)
}

func (fake *Metrics) IncPublishedCalls(stub func(string)) {
	fake.incPublishedMutex.Lock()
	defer fake.incPublishedMutex.Unlock()
	fake.IncPublishedStub = stub
}

func (fake *Metrics) IncPublishedArgsForCall(i int) string {
	fake.incPublishedMutex.RLock()
	defer fake.incPublishedMutex.RUnlock()
	argsForCall := fake.incPublishedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncReposScanned(arg1 int) {
	fake.incReposScannedMutex.Lock()
	fake.incReposScannedArgsForCall = append(fake.incReposScannedArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.IncReposScannedStub
	fake.recordInvocation("IncReposScanned", []interface{}{arg1})
	fake.incReposScannedMutex.Unlock()
	if stub != nil {
		fake.IncReposScannedStub(arg1)
	}
}

func (fake *Metrics) IncReposScannedCallCount() int {
	fake.incReposScannedMutex.RLock()
	defer fake.incReposScannedMutex.RUnlock()
	return len(fake.incReposScannedArgsForCall)
}

func (fake *Metrics) IncReposScannedCalls(stub func(int)) {
	fake.incReposScannedMutex.Lock()
	defer fake.incReposScannedMutex.Unlock()
	fake.IncReposScannedStub = stub
}

func (fake *Metrics) IncReposScannedArgsForCall(i int) int {
	fake.incReposScannedMutex.RLock()
	defer fake.incReposScannedMutex.RUnlock()
	argsForCall := fake.incReposScannedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncWebhookDelivery(arg1 string) {
	fake.incWebhookDeliveryMutex.Lock()
	fake.incWebhookDeliveryArgsForCall = append(fake.incWebhookDeliveryArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncWebhookDeliveryStub
	fake.recordInvocation("IncWebhookDelivery", []interface{}{arg1})
	fake.incWebhookDeliveryMutex.Unlock()
	if stub != nil {
		fake.IncWebhookDeliveryStub(arg1)
	}
}

func (fake *Metrics) IncWebhookDeliveryCallCount() int {
	fake.incWebhookDeliveryMutex.RLock()
	defer fake.incWebhookDeliveryMutex.RUnlock()
	return len(fake.incWebhookDeliveryArgsForCall)
}

func (fake *Metrics) IncWebhookDeliveryCalls(stub func(string)) {
	fake.incWebhookDeliveryMutex.Lock()
	defer fake.incWebhookDeliveryMutex.Unlock()
	fake.IncWebhookDeliveryStub = stub
}

func (fake *Metrics) IncWebhookDeliveryArgsForCall(i int) string {
	fake.incWebhookDeliveryMutex.RLock()
	defer fake.incWebhookDeliveryMutex.RUnlock()
	argsForCall := fake.incWebhookDeliveryArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncWebhookSignatureRejected() {
	fake.incWebhookSignatureRejectedMutex.Lock()
	fake.incWebhookSignatureRejectedArgsForCall = append(fake.incWebhookSignatureRejectedArgsForCall, struct {
	}{})
	stub := fake.IncWebhookSignatureRejectedStub
	fake.recordInvocation("IncWebhookSignatureRejected", []interface{}{})
	fake.incWebhookSignatureRejectedMutex.Unlock()
	if stub != nil {
		fake.IncWebhookSignatureRejectedStub()
	}
}

func (fake *Metrics) IncWebhookSignatureRejectedCallCount() int {
	fake.incWebhookSignatureRejectedMutex.RLock()
	defer fake.incWebhookSignatureRejectedMutex.RUnlock()
	return len(fake.incWebhookSignatureRejectedArgsForCall)
}

func (fake *Metrics) IncWebhookSignatureRejectedCalls(stub func()) {
	fake.incWebhookSignatureRejectedMutex.Lock()
	defer fake.incWebhookSignatureRejectedMutex.Unlock()
	fake.IncWebhookSignatureRejectedStub = stub
}

func (fake *Metrics) IncWebhookSkipped(arg1 string) {
	fake.incWebhookSkippedMutex.Lock()
	fake.incWebhookSkippedArgsForCall = append(fake.incWebhookSkippedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncWebhookSkippedStub
	fake.recordInvocation("IncWebhookSkipped", []interface{}{arg1})
	fake.incWebhookSkippedMutex.Unlock()
	if stub != nil {
		fake.IncWebhookSkippedStub(arg1)
	}
}

func (fake *Metrics) IncWebhookSkippedCallCount() int {
	fake.incWebhookSkippedMutex.RLock()
	defer fake.incWebhookSkippedMutex.RUnlock()
	return len(fake.incWebhookSkippedArgsForCall)
}

func (fake *Metrics) IncWebhookSkippedCalls(stub func(string)) {
	fake.incWebhookSkippedMutex.Lock()
	defer fake.incWebhookSkippedMutex.Unlock()
	fake.IncWebhookSkippedStub = stub
}

func (fake *Metrics) IncWebhookSkippedArgsForCall(i int) string {
	fake.incWebhookSkippedMutex.RLock()
	defer fake.incWebhookSkippedMutex.RUnlock()
	argsForCall := fake.incWebhookSkippedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) ObserveWebhookDispatchLatency(arg1 float64) {
	fake.observeWebhookDispatchLatencyMutex.Lock()
	fake.observeWebhookDispatchLatencyArgsForCall = append(fake.observeWebhookDispatchLatencyArgsForCall, struct {
		arg1 float64
	}{arg1})
	stub := fake.ObserveWebhookDispatchLatencyStub
	fake.recordInvocation("ObserveWebhookDispatchLatency", []interface{}{arg1})
	fake.observeWebhookDispatchLatencyMutex.Unlock()
	if stub != nil {
		fake.ObserveWebhookDispatchLatencyStub(arg1)
	}
}

func (fake *Metrics) ObserveWebhookDispatchLatencyCallCount() int {
	fake.observeWebhookDispatchLatencyMutex.RLock()
	defer fake.observeWebhookDispatchLatencyMutex.RUnlock()
	return len(fake.observeWebhookDispatchLatencyArgsForCall)
}

func (fake *Metrics) ObserveWebhookDispatchLatencyCalls(stub func(float64)) {
	fake.observeWebhookDispatchLatencyMutex.Lock()
	defer fake.observeWebhookDispatchLatencyMutex.Unlock()
	fake.ObserveWebhookDispatchLatencyStub = stub
}

func (fake *Metrics) ObserveWebhookDispatchLatencyArgsForCall(i int) float64 {
	fake.observeWebhookDispatchLatencyMutex.RLock()
	defer fake.observeWebhookDispatchLatencyMutex.RUnlock()
	argsForCall := fake.observeWebhookDispatchLatencyArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) SetRateLimitRemaining(arg1 int) {
	fake.setRateLimitRemainingMutex.Lock()
	fake.setRateLimitRemainingArgsForCall = append(fake.setRateLimitRemainingArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.SetRateLimitRemainingStub
	fake.recordInvocation("SetRateLimitRemaining", []interface{}{arg1})
	fake.setRateLimitRemainingMutex.Unlock()
	if stub != nil {
		fake.SetRateLimitRemainingStub(arg1)
	}
}

func (fake *Metrics) SetRateLimitRemainingCallCount() int {
	fake.setRateLimitRemainingMutex.RLock()
	defer fake.setRateLimitRemainingMutex.RUnlock()
	return len(fake.setRateLimitRemainingArgsForCall)
}

func (fake *Metrics) SetRateLimitRemainingCalls(stub func(int)) {
	fake.setRateLimitRemainingMutex.Lock()
	defer fake.setRateLimitRemainingMutex.Unlock()
	fake.SetRateLimitRemainingStub = stub
}

func (fake *Metrics) SetRateLimitRemainingArgsForCall(i int) int {
	fake.setRateLimitRemainingMutex.RLock()
	defer fake.setRateLimitRemainingMutex.RUnlock()
	argsForCall := fake.setRateLimitRemainingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Metrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.Metrics = new(Metrics)
