// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"sync"

	"github.com/bborbe/github-release-watcher/pkg/handler"
)

type WebhookMetrics struct {
	IncWebhookDeliveryStub        func(string)
	incWebhookDeliveryMutex       sync.RWMutex
	incWebhookDeliveryArgsForCall []struct {
		arg1 string
	}
	IncWebhookSignatureRejectedStub        func()
	incWebhookSignatureRejectedMutex       sync.RWMutex
	incWebhookSignatureRejectedArgsForCall []struct {
	}
	IncWebhookSkippedStub        func(string)
	incWebhookSkippedMutex       sync.RWMutex
	incWebhookSkippedArgsForCall []struct {
		arg1 string
	}
	ObserveWebhookDispatchLatencyStub        func(float64)
	observeWebhookDispatchLatencyMutex       sync.RWMutex
	observeWebhookDispatchLatencyArgsForCall []struct {
		arg1 float64
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *WebhookMetrics) IncWebhookDelivery(arg1 string) {
	fake.incWebhookDeliveryMutex.Lock()
	fake.incWebhookDeliveryArgsForCall = append(fake.incWebhookDeliveryArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncWebhookDeliveryStub
	fake.recordInvocation("IncWebhookDelivery", []interface{}{arg1})
	fake.incWebhookDeliveryMutex.Unlock()
	if stub != nil {
		fake.IncWebhookDeliveryStub(arg1)
	}
}

func (fake *WebhookMetrics) IncWebhookDeliveryCallCount() int {
	fake.incWebhookDeliveryMutex.RLock()
	defer fake.incWebhookDeliveryMutex.RUnlock()
	return len(fake.incWebhookDeliveryArgsForCall)
}

func (fake *WebhookMetrics) IncWebhookDeliveryCalls(stub func(string)) {
	fake.incWebhookDeliveryMutex.Lock()
	defer fake.incWebhookDeliveryMutex.Unlock()
	fake.IncWebhookDeliveryStub = stub
}

func (fake *WebhookMetrics) IncWebhookDeliveryArgsForCall(i int) string {
	fake.incWebhookDeliveryMutex.RLock()
	defer fake.incWebhookDeliveryMutex.RUnlock()
	argsForCall := fake.incWebhookDeliveryArgsForCall[i]
	return argsForCall.arg1
}

func (fake *WebhookMetrics) IncWebhookSignatureRejected() {
	fake.incWebhookSignatureRejectedMutex.Lock()
	fake.incWebhookSignatureRejectedArgsForCall = append(fake.incWebhookSignatureRejectedArgsForCall, struct {
	}{})
	stub := fake.IncWebhookSignatureRejectedStub
	fake.recordInvocation("IncWebhookSignatureRejected", []interface{}{})
	fake.incWebhookSignatureRejectedMutex.Unlock()
	if stub != nil {
		fake.IncWebhookSignatureRejectedStub()
	}
}

func (fake *WebhookMetrics) IncWebhookSignatureRejectedCallCount() int {
	fake.incWebhookSignatureRejectedMutex.RLock()
	defer fake.incWebhookSignatureRejectedMutex.RUnlock()
	return len(fake.incWebhookSignatureRejectedArgsForCall)
}

func (fake *WebhookMetrics) IncWebhookSignatureRejectedCalls(stub func()) {
	fake.incWebhookSignatureRejectedMutex.Lock()
	defer fake.incWebhookSignatureRejectedMutex.Unlock()
	fake.IncWebhookSignatureRejectedStub = stub
}

func (fake *WebhookMetrics) IncWebhookSkipped(arg1 string) {
	fake.incWebhookSkippedMutex.Lock()
	fake.incWebhookSkippedArgsForCall = append(fake.incWebhookSkippedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncWebhookSkippedStub
	fake.recordInvocation("IncWebhookSkipped", []interface{}{arg1})
	fake.incWebhookSkippedMutex.Unlock()
	if stub != nil {
		fake.IncWebhookSkippedStub(arg1)
	}
}

func (fake *WebhookMetrics) IncWebhookSkippedCallCount() int {
	fake.incWebhookSkippedMutex.RLock()
	defer fake.incWebhookSkippedMutex.RUnlock()
	return len(fake.incWebhookSkippedArgsForCall)
}

func (fake *WebhookMetrics) IncWebhookSkippedCalls(stub func(string)) {
	fake.incWebhookSkippedMutex.Lock()
	defer fake.incWebhookSkippedMutex.Unlock()
	fake.IncWebhookSkippedStub = stub
}

func (fake *WebhookMetrics) IncWebhookSkippedArgsForCall(i int) string {
	fake.incWebhookSkippedMutex.RLock()
	defer fake.incWebhookSkippedMutex.RUnlock()
	argsForCall := fake.incWebhookSkippedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *WebhookMetrics) ObserveWebhookDispatchLatency(arg1 float64) {
	fake.observeWebhookDispatchLatencyMutex.Lock()
	fake.observeWebhookDispatchLatencyArgsForCall = append(fake.observeWebhookDispatchLatencyArgsForCall, struct {
		arg1 float64
	}{arg1})
	stub := fake.ObserveWebhookDispatchLatencyStub
	fake.recordInvocation("ObserveWebhookDispatchLatency", []interface{}{arg1})
	fake.observeWebhookDispatchLatencyMutex.Unlock()
	if stub != nil {
		fake.ObserveWebhookDispatchLatencyStub(arg1)
	}
}

func (fake *WebhookMetrics) ObserveWebhookDispatchLatencyCallCount() int {
	fake.observeWebhookDispatchLatencyMutex.RLock()
	defer fake.observeWebhookDispatchLatencyMutex.RUnlock()
	return len(fake.observeWebhookDispatchLatencyArgsForCall)
}

func (fake *WebhookMetrics) ObserveWebhookDispatchLatencyCalls(stub func(float64)) {
	fake.observeWebhookDispatchLatencyMutex.Lock()
	defer fake.observeWebhookDispatchLatencyMutex.Unlock()
	fake.ObserveWebhookDispatchLatencyStub = stub
}

func (fake *WebhookMetrics) ObserveWebhookDispatchLatencyArgsForCall(i int) float64 {
	fake.observeWebhookDispatchLatencyMutex.RLock()
	defer fake.observeWebhookDispatchLatencyMutex.RUnlock()
	argsForCall := fake.observeWebhookDispatchLatencyArgsForCall[i]
	return argsForCall.arg1
}

func (fake *WebhookMetrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *WebhookMetrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handler.WebhookMetrics = new(WebhookMetrics)
